# Generated by Django 4.0.5 on 2022-06-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Status', max_length=100)),
                ('Status', models.BooleanField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
