# Generated by Django 4.0.5 on 2022-06-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_apistatus_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistatus',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
