# Generated by Django 4.0.5 on 2022-07-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tradeinfo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinfo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
