# Generated by Django 4.0.5 on 2022-07-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tradeinfo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equity', models.FloatField()),
                ('Balance', models.FloatField()),
                ('Time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
