# Generated by Django 4.0.5 on 2022-07-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_feed_balance_remove_feed_equity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feeds', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
